### ISSUE TITLE
Different count events after gating FlowJo/Flowkit

### ISSUE THREAD

**Issue by DomenicoDB** [whitews/FlowKit#113]
Dear Scott,

we have runned this code, as suggested in tutorials:

`session=fk.Session() `
`session.import_flowjo_workspace(wsp_path)`
`session.add_samples(sample_path,'All Samples')`
`session.get_sample_groups()`
`sample_group = 'All Samples'`
`sample_list = session.get_group_sample_ids(sample_group)`
`session.analyze_samples(sample_group, verbose=True)`
`

We have as results in Flowkit:
#EV TOTAL: 869133
#EV Gate1: 490825
#EV Gate2:484230
#EV Gate3: 255195

But in FlowJo we have as results:
#EV TOTAL: 869133
#EV Gate1: 493945 
#EV Gate2: 486806
#EV Gate3: 256044

We have used the same files  for analysis (fcs files and FlowJo-generated wsp) and we don't understand the reason of this difference (count event), We used FlowJo 10.8.1.
Do you have any suggestion?

Thanks a lot!

**Comment by whitews** [comment]
Hi,

This is likely due to the fact that FlowJo reports some statistics based on binned data. They mention this at the bottom of [this doc page](https://docs.flowjo.com/flowjo/workspaces-and-samples/ws-statistics/). This is true for polygon and ellipse gates. Rectangle gates don't use the binning method and are exact in FlowJo.

You can see how this works using the workspace simple_poly_and_rect_v2_poly50.wsp in the simple_line_example (in examples/data of this repo). I created those to test exactly what was happening when I first discovered this same thing years ago. 

If you open that workspace & load the sample, you will find the sample event data consists of 100 events placed along a line in channel_B. The workspace has 2 gates, a polygon & rectangle gate, both of which are place very carefully to be below the events such that no events are included in either gate. However, if you change the channel_B transform from linear to log, you will see the polygon gate will have 100% of the events. 

There is no way the polygon boundary value, being lower than the event value can ever be transformed to be above those event values (all the vertex coordinates and events get transformed use the same function). The reason this happens for the different transform is that the binning will changed based on the transform.

I have also verified this behavior with the FlowJo dev team. In my opinion, the reason the binning is done is primarily b/c FlowJo is a GUI application and the results need to be calculated more quickly since there is a user waiting. FlowKit doesn't have this expectation and so calculates the exact values.

One final note, because of this binning you will tend to see that FlowJo's numbers for polygon gates will tend to slightly overestimate the gated events. Once the 2-D space is binned into rectangles there are no actually events displayed (just counts in a bin). You can see this in the scatterplots that everything is a small rectangle. Anyway, if a polygon boundary passes through a rectangle then all the events in that rectangle are marked as inside the gate.

Apologies for the long answer, but it can be difficult to explain...it took me some time to understand it. Hope this helps,
Scott
