### ISSUE TITLE
Offset error not detected

### ISSUE THREAD

**Issue by andreas-wilm** [whitews/FlowKit#136]
Hi Scott

**Describe the bug**

Flowkit reads files with wrong data offset without failing. The wrong offset is not detected (irrespective of the `ignore_offset_error` setting) and data is read wrongly.  This is pretty much identical to #65 (which I couldn't reopen). Let me know if I should transfer this to FlowIO.

**Code To Reproduce**

##### Create a dummy file
```
In [1]: import flowkit as fk
...
In [73]: df
Out[73]:
pnn CD3_TotalC CD4_TotalC
pns CD3_TotalC CD4_TotalC
0          0.0        0.0

In [74]: sample = fk.Sample(df)

In [75]: sample.export("zeros.fcs", source='raw')
...
```

##### Inspect the file and create and artificial wrong data offset
```
$ cat zeros.fcs
FCS3.1         256     545     546     553       0       0                                                                                                                                                                                                      /$BEGINANALYSIS/0/$BEGINDATA/546/$BEGINSTEXT/0/$BYTEORD/1,2,3,4/$DATATYPE/F/$ENDANALYSIS/0/$ENDDATA/553/$ENDSTEXT/0/$MODE/L/$NEXTDATA/0/$PAR/2/$TOT/1/$P1B/32/$P1E/0,0/$P1G/1.0/$P1R/262144/$P1N/CD3_TotalC/$P1S/CD3_TotalC/$P2B/32/$P2E/0,0/$P2G/1.0/$P2R/262144/$P2N/CD4_TotalC/$P2S/CD4_TotalC/%

$ cat zeros.fcs zeros_corrupt.fcs
$ vi zeros_corrupt.fcs
$ cat zeros_corrupt.fcs
FCS3.1         256     545     546     553       0       0                                                                                                                                                                                                      /$BEGINANALYSIS/0/$BEGINDATA/545/$BEGINSTEXT/0/$BYTEORD/1,2,3,4/$DATATYPE/F/$ENDANALYSIS/0/$ENDDATA/552/$ENDSTEXT/0/$MODE/L/$NEXTDATA/0/$PAR/2/$TOT/1/$P1B/32/$P1E/0,0/$P1G/1.0/$P1R/262144/$P1N/CD3_TotalC/$P1S/CD3_TotalC/$P2B/32/$P2E/0,0/$P2G/1.0/$P2R/262144/$P2N/CD4_TotalC/$P2S/CD4_TotalC/

# Note the offset BEGINDATA and ENDDATA
```

##### Load the corrupted data

```
In [77]: sample = fk.Sample("zeros_corrupt.fcs", ignore_offset_error=False)
# this should fail. worse of all, the read data is wrong:

In [78]: df = sample.as_dataframe(source="raw")

In [79]: df
Out[79]:
pnn    CD3_TotalC CD4_TotalC
pns    CD3_TotalC CD4_TotalC
0    6.586103e-44        0.0

# Note the random first value. You get the same result with ignore_offset_error=True
```

**Expected behaviour**

1. Reading zeros_corrupt.fcs should fail with `ignore_offset_error=False`. 
1. Reading zeros_corrupt.fcs with `ignore_offset_error=True` should use the correct offset, reading the data correctly. 

**Desktop (please complete the following information):**
 - OS: OSX 12.5.1
 - Python version 3.9.12
 - FlowKit version 0.9.1
 - FlowIO version 1.0.1

**Comment by Arshad9999** [comment]
Since you are trying to read the FCS file, you can use FlowIO to read the file and check for the offset errors, if you want to make sure that the file offset is correct or not. You can also use FlowKit to read the file and do the data analysis but it will not be able to detect the offset errors.
It's worth noting that if you want to detect the offset errors or you want to read the data from the FCS file in a more detailed way, you should use FlowIO, otherwise, you can use FlowKit for the analysis of the data.

**Comment by andreas-wilm** [comment]
Thanks @Arshad9999. I think FlowKit should in theory be able to detect these errors, because the values in the header and text segment are clearly different. At the very least, the error should cascade up from FlowIO (which FlowKit is using AFAIK)

**Comment by whitews** [comment]
@andreas-wilm 

You are correct that this is mostly a FlowIO issue but does have obvious implications for the FlowKit Sample class. I'll just recap what FlowIO is doing and why, then discuss what we should do in this case.

### What FlowIO is doing

The FlowData class in FlowIO uses the header values to locate the text section. Then, the text segment is parsed and the values in the text metadata are used to locate the data section. Note, the header values for the data offset are only used if there is a KeyError in looking up the BEGINDATA & ENDDATA tags in the text metadata.

### Why FlowIO does it this way

This is done because the header segment limits each offset value to 8 bytes, which means the header cannot properly provide offsets for locations beyond 99,999,999 bytes. In those cases, the header value will be zero and the parser must rely on the text segment for the offset values.

My rationale at the time was that FlowIO would use the text section for the source of the data offsets since you have to do this anyway for large files. However, there is no internal comparison made in the FlowData class between the header and text values to ensure they are the same or only different for the large file case.

### Why FlowKit doesn't allow the comparison

@Arshad9999 is correct that you can use the FlowData object to do the comparison yourself because the FlowData object has attributes for both the header and the text section (both are dictionaries). However, this is not currently possible in FlowKit because the Sample constructor does not retain the FlowData object. 

I purposely left the 'header' attribute out of the Sample class to avoid confusion, since many in the flow world call the text section the "header". I also didn't call the text section "text", instead choosing the term "metadata" for the attribute. This is all inline with FlowIO being the low-level library using technically correct terms according to the specification, and FlowKit targeting high-level analysis concepts. 

### ***So what should we do about this case?***

**Proposal 1**

Add the header attribute to the FlowKit Sample class and users can do their own comparison.

Pros: This is easy to implement and doesn't cause any breaking changes to the Sample class API
Cons: Non-technical FlowKit uses may not even know to check this and the "header" attribute's existence may be confusing.

**Proposal 2**

The FlowIO FlowData constructor throws an error for this case.

Pros: Safely eliminates the case from causing unknown behaviour or analysis results downstream.
Cons: Prevents the Sample class (and FlowData class) constructor from completing such that even metadata inspection of such files is not possible. 

**Proposal 3**

The FlowIO FlowData constructor issues a custom warning for this case.

Pros: Provides users with a reasonable indication that something may be wrong & allows reading at least some portion of the FCS file contents (i.e. the metadata).
Cons: Not as easily caught as an error/exception, esp. for automated pipelines.

----

I'm curious what you all think of these options and open to other ideas. As always, thanks for using the libraries and reporting these issues!  

-Scott

**Comment by andreas-wilm** [comment]
Thanks for the detailed explanation! And many thanks for including your users in the decision process!

Since users run the risk of unknowingly (!) using corrupted data (all data values change because of the wrong offset!) I'm definitely for throwing an error, i.e vote for proposal 2, which throws an error. 

Can I (as someone who doesn't fully understand how this works internally) ask if an internal comparison in the FlowData class between the header and text values could be done? This should throw an exception if the data offset values are differently set in header and text. The only exception would be in the case of big files where the offsets can't be properly stored in the header segment and are set to 0 (if I remember correctly). On mismatch this should throw an error. Is this in fact proposal 2?

Many thanks for dealing with this,
Andreas

**Comment by whitews** [comment]
Andreas,

Yes, you have described proposal 2, and yes the header & text values for the data offset can be quite easily compared internally. I was leaning towards option 2 or 3, and it sounds like FlowIO raising a custom Exception might be the better solution. The only remaining question is whether to allow an option to override the error. This would be helpful in a scenario where there is a discrepancy but the text values are correct, and parsing the data would be done correctly.

I'm curious if you actually ran into this in a real FCS file and if so, where did the file come from or was there a tool that modified to be this way?

As for including users in the process, I actually wish there were an easy way to poll all the FlowKit users for more development ideas / decisions. There have been many design decisions & features where user feedback would have been helpful.

**Comment by andreas-wilm** [comment]
Thanks Scott.

These files come from FlowJo (varying versions)! Unfortunately we can't reproduce the problem, but luckily we see this rarely.

FlowCore throws an error on reading these files. When setting `ignore.text.offset` to TRUE, it uses the values in the header segment and just warns:  "_The HEADER and TEXT segment defined different starting point (x:y) to read the data_". Likewise for the end point.

I think this solution makes sense. The exception are cases of big files with header values set to 0.

Regarding user involvement: I've seen other devs using Twitter polls. But you likely need a larger user base for this and people would have to follow your account. How about having an always open Git issue which interested people can sign up for and where you just keep polling?

**Comment by whitews** [comment]
Andreas,

I like that solution. I will update FlowIO's FlowData constructor to mirror that option. It will be in the next patch update of FlowIO and then the FlowKit dependency will be updated in the upcoming FlowKit 1.0 release.

The dedicated GitHub issue is a good idea as well, think I will try that.

Thanks again for reporting and contributing ideas!
-Scott

**Comment by whitews** [comment]
Andreas,

In implementing this, it occurred to me that we may need 2 separate options to cover all the possible cases. Here's the updated plan:

By default, FlowIO will use the TEXT data offsets and load a file normally when the HEADER & TEXT agree or if the HEADER value is 0 for large files.

For a discrepancy in the 2 values, FlowIO will raise an Exception when the discrepancy is not due to the large file scenario.

For the case where the user wants to ignore a discrepancy and use the TEXT value they can force the loading of the file with a new `ignore_offset_discrepancy` option (which defaults to False).

For the case where the user wants to ignore a discrepancy and use the HEADER value they can force the loading of the file with a new `use_header_offsets` option (which also defaults to False).

Setting both `ignore_offset_discrepancy` & `use_header_offsets` to True will be equivalent to just setting `use_header_offsets` to True. 

----

I think that should cover all the possibilities and not be too confusing.

**Comment by whitews** [comment]
After more testing, I'm comfortable with this API for the next release, closing for now.
