### ISSUE TITLE
How to pass data to Matplotlib instead of Bokeh?

### ISSUE THREAD

**Issue by huivni84** [whitews/FlowKit#138]
Is there any way to pass the transformed data to Matplotlib instead of Bokeh?

While I like the general appearance of the density plots, the output to the browser seems unnecessary to me and also the adjustment of the plots regarding title, aspect ratio and, very simply, packing several plots into one figure is not trivial with Bokeh.

**Comment by whitews** [comment]
Hi,

I originally used Matpotlib for the scatter plots, but flow data has too many data points and the performance wasn't great. I found Bokeh to be much more performant and the interactivity was a nice bonus. While FlowKit provides some visualization features, the primary focus is on analysis...there are just too many variations on the ways to visualize data.

The Sample class has options for the extraction of event data in a variety of forms: raw data before compensation ("raw"), only compensated ("comp"), or optionally compensated + transformed ("xform"). And you can get those events as a NumPy array or Pandas DataFrame. From there you can quite easily create matplotlib plots. If you are having an issue retrieving those, please let me know.

Also, I intentionally return a Bokeh Figure instance in all the plot functions / methods for the exact reason you mention, so that a browser is **not** required and the plots can be handled programmatically. Whether Matplotlib or Bokeh is easier to use is subjective. After some learning curve, I actually prefer the Bokeh API, especially regarding putting multiple plots into a single figure. Check out the code [for the scatter plot matrix](https://github.com/whitews/FlowKit/blob/master/flowkit/_models/sample.py#L933). You basically make an array of figures, then call gridplot and you are done!

If there are some pass-through arguments you would like for controlling Bokeh Figure properties (e.g. aspect ratio), let me know. I'm more open to something like that than providing multiple ways to do the same thing in different libraries.

Hope this helps,
Scott

**Comment by huivni84** [comment]
Thanks, the hint towards the scatter matrix helped me make use of Bokeh for my purpose.
