### ISSUE TITLE
Importing FCS files into Flowkit

### ISSUE THREAD

**Issue by tinsleykw** [whitews/FlowKit#193]
**Describe the bug**
I am trying to read in my FCS files and I keep getting the following error:

IsADirectoryError: [Errno 21]

I copy the file path to the FCS files into fk.Sample('my specific file path') then I get the above error.

**Code To Reproduce**
Code to reproduce the behavior:
```
import flowkit as fk
import  bokeh
import pandas as pd
fk.__version__

...
```

**Expected behavior**
I expect some notification that my FCS files are recognized

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Sonoma 14.4.1]
 - Python version [3.11.5]
 - FlowKit version [1.1.0]

**Additional context**

**Comment by whitews** [comment]
Hi,

I think the issue here is that you may be giving a directory path instead of a path to a single FCS file as the argument to the `Sample` class. A `Sample` instance represents a single FCS file. [See the docs on the `Sample` class](https://flowkit.readthedocs.io/en/latest/sample.html#sample-class) for more information about the parameters.

Note there is also a utility function `load_samples` that provides a convenient way to load multiple FCS files from a single directory path. [See the doc on `load_samples` here](https://flowkit.readthedocs.io/en/latest/functions.html#flowkit.load_samples).

Let me know if that gets you past the error.

-Scott
