### ISSUE TITLE
Non-rectangular gates introduce errors in get_analysis_report()

### ISSUE THREAD

**Issue by nettilor** [whitews/FlowKit#194]
Hi!

I was loading a FlowJo workspace and using analyze_samples() and then get_analysis_report() to get counts out of my FlowJo file. I noticed rectangular gates report the events that fall into the gate correctly but for other gates (I tried ellipses and polygons) the events that Flowkit assigns to the gates are always less than FlowJo.

See screenshot here, I used the 8_color_data_set. FlowJo counts and Flowkit counts from get_analysis_report() do not match
<img width="1226" alt="SCR-20240428-ljjn" src="https://github.com/whitews/FlowKit/assets/125505698/88f0091e-0040-453a-8963-f04e552f8bcc">

Edit: this also happens if you just try to read the file 8_color_ICS_with_ellipse.wsp included in the dataset. For the non-rectangular gates the counts won't match

Thank you for your work!

Some more info if useful:
- OS: macOS Sonoma 14.4.1 (23E224)
- Python: 3.12.3
- Flowkit: 1.1.1
- FlowJo: 10.10.0

**Comment by whitews** [comment]
Hi @nettilor 

Yes, this due to FlowJo applying gates on binned data instead of the actual event data. It does this for polygon and ellipse gates but the rectangular gates (and simple line thresholds) use the event data b/c it is easier to calculate. FlowKit uses the event data for all gates without binning. I wrote a more detailed explanation here:

**Comment by nettilor** [comment]
Yes! thank you!
