### ISSUE TITLE
BiexTransform and MFI values

### ISSUE THREAD

**Issue by nettilor** [whitews/FlowKit#195]
Hi!

I was trying to calculate MFI values as shown in the documentation starting from a FlowJo workspace. I understand the samples are compensated and transformed according to the workspace when using get_gate_events() but the values for the BiexTransform in FlowJo and Flowkit seem to be orders of magnitude different. I looked through the source code a bit (thank you for the very clean code) and I cannot make sense of why this is.

I see this also using plot_scatter for instance:
<img width="1326" alt="image" src="https://github.com/whitews/FlowKit/assets/125505698/a4a37219-20dd-4877-b5b0-fda26219d24a">

I feel I just don't know enough about the transform to know why this is.

thank you for your help!!

**Comment by whitews** [comment]
Hi @nettilor,

Those look comparable to me given the FlowKit plot is probably sub-sampled. Are you referring to the differences in the magnitude of the axis values?

-Scott

**Comment by nettilor** [comment]
Yes exactly!
I am confused as how with the same transform the values I get are in the 10^3 range in Flowkit while the FlowJo ones span orders of magnitude

- Lorenzo

**Comment by whitews** [comment]
Hi Lorenzo,

Ahh, so this is a little confusing. FlowJo always displays axis values in the original untransformed space. The data is still displayed transformed but the axis values are then mapped back to the original space and annotated on the axis in the scientific notation format seen in your screenshot. For most flow data, the fluoro channels have a 32 bit allocation per value but the cytometer range is typically limited to 18 bits (i.e. 262144). That equates to 2.6 x 10^5, and that's in the ball park of the upper range you see.

FlowKit, on the other hand, always displays transformed values on the plot axes. One reason for this is that it is simple to implement and straight-forward. The other reason is because gate boundary coordinates are specified in the transformed space (if the channel data specifies a transform). So if you are looking through an array of transformed event data values and see numbers in the transformed data range, it becomes confusing IMO to then reference a plot that is displaying a different set of values.

I hope that explanation makes sense. Basically, I made the judgement call that while FlowKit is not intended as a GUI replacement it is very helpful to have some basic visualization of the data and gates. And, that visualization has more of a programmatic context than a flow analyst using FlowJo.

And a related note about the Transform classes. Most of the transforms will scale data to 0 and 1, where the lower and upper bounds in the given data is set by the transform parameters. The `WSPBiexTransform` is an exception. Any `WSP` prefixed transform in FlowKit is an implementation of a FlowJo transform. In the case of the FlowJo's biex transform, data is scaled to 0 and 4096 (not 0 to 1). I don't know exactly why that is but just wanted to point it out since it's an oddball in the FlowKit transforms.

I really should write an FAQ for all of these implementation details :thinking: 

Regards,
Scott

**Comment by nettilor** [comment]
Perfect! It does.
So manually getting events and applying only the compensation matrix is the solution to this. I think this might be very useful information in the Advanced Tutorials page for computing MFIs. 
Also, maybe having a 'source' argument for workspace.get_gate_events() so to choose what form of the events is returned might be useful and match functionality found in other functions in Flowkit.

Anyways, thank you so much for all your help Scott! This was extremely useful!

Best,
Lorenzo

**Comment by whitews** [comment]
Great, glad to help! And good ideas about adding to the MFI tutorial and the source kwarg for get_gate_events.
