### ISSUE TITLE
Gate Name not correctly display

### ISSUE THREAD

**Issue by NTNguyen13** [whitews/FlowKit#24]
I load this gatingML file from cytobank: [CytExp_231400_Gates_v1.zip](https://github.com/whitews/FlowKit/files/3200488/CytExp_231400_Gates_v1.zip)

I import it by 

`g_strat = fk.GatingStrategy('./cytobank/Gating.xml')
`

but when I check the gate name, it's not correct, and also the hierarchical seems to be wrong.

This is the gating strategy diagram

![image](https://user-images.githubusercontent.com/39985901/58064389-ccb51b80-7bbc-11e9-9a30-aa12cdbc3e52.png)

Could you please help me on this problem? Thank you

**Comment by whitews** [comment]
I'll check it out. Can you tell me which gate name is incorrect and what the correct name should be?

**Comment by NTNguyen13** [comment]
When I check the gate name by `g_strat.gates` , it only shows the type of gate correctly, the name is show as some serial numbers. For example: Gate_43100124_Tm9uLWJlYWRz': RectangleGate(Gate_43100124_Tm9uLWJlYWRz, parent: None, dims: 2)

**Comment by whitews** [comment]
Just had a look at the GatingML file. Those oddly named gates are correct. For example the first gate in the file has the opening tag:

    <gating:RectangleGate gating:id="Gate_43100124_Tm9uLWJlYWRz">

Nested inside that tag are tags that are not part of the GatingML specification, like <cytobank>...</cytobank> which contain other metadata, including what looks to the the text strings for the gate names you are looking for. The one for the gate above was named "Non-beads".

Unfortunately, it seems many flow applications export these "semi" compliant files. I don't know why they would go through the trouble of making a file that is essentially compliant and not use the human readable names for the id property instead of these computer generated text strings. 

Hope this helps to at least explain what is happening here.

**Comment by NTNguyen13** [comment]
Thank you for explanation, I'm also confused by these semi-complicant files, I will find a work-around.

**Comment by whitews** [comment]
You're welcome. As much as I am tempted to provide code to translate these types of files to valid GatingML, or at least more usable forms, I feel that would only prevent their creators from producing correct GatingML data formats. One of the major goals of this project is to encourage the use of the open standards.
