### ISSUE TITLE
Unable to apply a .wsp gating strategy to a Sample()

### ISSUE THREAD

**Issue by ncthomas** [whitews/FlowKit#47]
Great work I'm looking to apply a FlowJo 10 .wsp gating strategy to a Sample() object, as I am unable to find a way to export a suitable FlowJo xml strategy (FlowJo 9 xml format is not readable and FlowJo 10 doesn't seem to offer me an option to export a gating strategy as xml).

**Approaches tried so far**

1. Export XML from FlowJo 9, which raises an error to say <FlowJo 10 is not supported.
2. Export FlowJo 10 .wsp and use with parse_gating_xml() which of course throws an ValueError to say that the .wsp is not an xml, and to use parse_wsp().
3. Unable to find documentation for parse_wsp() on how to apply a gating strategy to a Sample() object.

**Desired solution**
Preferably, to use an xml gating strategy from FlowJo 9 (appreciate that you will likely no support that though).
Otherwise, another tutorial notebook to show how to use a FlowJo gating strategy from FlowJo 10 (either a .wsp or assistance on what gating strategy exports from FlowJo 10 are suitable to use with FlowKit).

Thanks in advance, great work on the package. Your visualisations using bokeh look great.

**Comment by whitews** [comment]
Hi Niclas,

Thanks for the kind words, and for using FlowKit. Adding support for FlowJo workspaces has been quite an ordeal. You are correct that the FlowJo 9 files will not be supported...the .jo files are binary and the XML exports are too different. However, I am currently trying to support as many features of the FlowJo 10 .wsp files within FlowKit. These files are XML text files, though they are not compatible with the GatingML 2.0 specification and their format is not documented. With the lack of documentation it is taking some time to figure out all the nuances of how they are constructed.

Regarding your question about how to import a FlowJo 10 wsp file. You are right that the output from the `parse_wsp` function is not well-documented (or documented at all, eeks!). That function returns a rather complex dictionary of FlowKit objects that can be used to build a GatingStrategy. However, the better way is to create a blank Session and use the Session method `import_flowjo_workspace` with the path to the wsp file.

I don't recall exactly when the `import_flowjo_workspace` method was added, but you may want to clone the latest version from the `develop` branch. There have been quite a few updates since the 0.4.0 release. Also, I have just added a new notebook example and some sample FCS files showing how to load a FlowJo 10 workspace file and how someone would replicate the gating strategy programmatically in FlowKit. You can find that notebook [here in the examples folder](https://github.com/whitews/FlowKit/blob/develop/examples/flowkit-session-replicate-flowjo-wsp-example.ipynb). Check that out and let me know if it helps you import your file.

Kind regards,
Scott

BTW, I have discovered that, starting in version 10.6.2, FlowJo 10 will open version 9 .jo files, though it doesn't seem to retain the details of the FCS files. Still, this is useful for converting old workspaces to FJ 10 without having to manually redo all the gates.

**Comment by ncthomas** [comment]
Thanks for the quick response. I've taken the latest commit of develop and followed the tutorial notebook and get the following error: -

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-87a3c94033b1> in <module>
      1 session = flowkit.Session(fcs_path)
----> 2 session.import_flowjo_workspace(wsp_path)

~/projects/flow_py/.venv/lib/python3.7/site-packages/flowkit/_models/session.py in import_flowjo_workspace(self, workspace_file_or_path)
    214                 # TODO: change keys to tuple of gate ID, parent ID so gates can be "reused" for different branches
    215                 for gate_node in data_dict['gates'].descendants:
--> 216                     gs.add_gate(gate_node.gate)
    217 
    218                 matrix = data_dict['compensation']

~/projects/flow_py/.venv/lib/python3.7/site-packages/flowkit/_models/gating_strategy.py in add_gate(self, gate)
     66             if len(matching_nodes) == 0:
     67                 # TODO: could be in a quadrant gate
---> 68                 raise ValueError("Parent gate %s does not exist in the gating strategy" % parent_id)
     69             elif len(matching_nodes) > 1:
     70                 raise ValueError("Multiple gates exist matching parent ID %s, specify branch" % parent_id)

ValueError: Parent gate CD3, CD45 subset does not exist in the gating strategy
```
I tried to follow your notebook with the latest release on master and it runs without error, but doesn't seem to recognise any populations, as after I run
```
session.analyze_samples('default')
session.get_gate_hierarchy('default')
```
I only get 
```
'root'
```
Any help greatly appreciated - happy to share the 2 fcs files and corresponding .wspif that helps diagnose the issue.

**Comment by whitews** [comment]
Yes, having the files would be helpful to track down what the problem is. Can you share a Google Drive or DropBox link? 

Also, what OS are you using and what version of Python?

**Comment by ncthomas** [comment]
Great thanks, available here for a couple of days - https://drive.google.com/file/d/1ZskiKRKkKaSDnmfqDVqP7yDaUFE8ZY4K/view?usp=sharing

I'm on macOS Catalina 10.15.4, Python 3.7.0.

**Comment by whitews** [comment]
Thanks, got the link and requested access from my gmail.

**Comment by ncthomas** [comment]
Perfect, have granted access now

**Comment by whitews** [comment]
Niclas, I downloaded the files and found the problem. The wsp file should now import correctly in the latest commit of the develop branch. 

However, there's another issue I need to address before you'll get accurate gating results in your file. I have not yet added support for converting log transforms in wsp files. I'm working on this now and, if the FlowJo implementation of the log transform is straight-forward, it should be done later today.

**Comment by ncthomas** [comment]
Brilliant, thanks very much Scott

**Comment by whitews** [comment]
Niclas, I've added support for the FlowJo log implementation, and fixed a couple other small issues. Your workspace should work now and produce all the plots and results without issue. 

Part of the update was changing the mechanism by which ambiguous gate names are referenced (like CD49a in your data). Can you re-run the notebook code and check that the event counts are what you expect? 

Below is a snippet of code showing the new way to plot gates using the full gate paths:

```
fks_fj.analyze_samples(sample_grp, verbose=True)

results = fks_fj.get_gating_results(sample_grp, sample_id)

for (samp_id, gate_id), row in results.report.iterrows():    
    p = fks_fj.plot_gate(
        sample_grp, 
        samp_id, 
        gate_id,
        gate_path=row.gate_path,
        x_min=0, 
        x_max=1.2, 
        y_min=0, 
        y_max=1.2
    )
    show(p)
```

**Comment by ncthomas** [comment]
Perfect, works nicely thanks Scott
