### ISSUE TITLE
Cannot use pandas Dataframe with fk.Sample

### ISSUE THREAD

**Issue by SalamHerkules** [whitews/FlowKit#98]
**Describe the bug**
Cannot use pandas Dataframe objects as a source of data when defining the Sample.

**Code To Reproduce**
Code to reproduce the behavior:
```
import bokeh
from bokeh.plotting import show
import matplotlib.pyplot as plt
import os
import flowkit as fk
import pandas as pd
import numpy as np
from IPython.display import display
import pickle

df = pd.DataFrame([44434214.0], columns = ['A'], dtype=np.float64)
df
sample = fk.Sample(df)
sample.as_dataframe(source="raw”)
```

**Expected behavior**
Sample object is created. 

**Screenshots**

![Screenshot 2022-04-22 at 17 35 22](https://user-images.githubusercontent.com/104216211/164747311-d1333c3f-9832-47ca-ad30-727bdd721e2b.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina, Version 10.15.7
 - Python version: Python 3.10.4
 - FlowKit version:  0.8.2

**Additional context**
Just to be sure I tested the loading from pandas Dataframe with an example (also in **Code To Reproduce**) I found in this discussion. Still no luck.

**Comment by whitews** [comment]
I copied your code and it didn't run for me because of the presence of the odd closing quote character in:

"raw”

When I change that character to a regular quote it works. Here's the minimum working example:

```
import numpy as np
import pandas as pd
import flowkit as fk

df = pd.DataFrame([44434214.0], columns = ['A'], dtype=np.float64)

sample = fk.Sample(df)

df2 = sample.as_dataframe(source="raw")

print(df2.shape)
```

Does this code work or do you still get an error?

**Comment by SalamHerkules** [comment]
Sorry for that one, mistake when copying the code. I tried it with "raw" and 'raw', both give the same error.

**Comment by whitews** [comment]
Ok, I had to re-install 0.8.2 from scratch & now see what is happening. The requirements didn't lock down the version of FlowIO and I recently updated that library to 1.0. That new version has API changes. You likely have that version installed.

To fix it:

```
pip uninstall flowio
pip install "flowio==0.9.14"
```

Let me know if that works.

Also, note that a new release of FlowKit (v0.9.0) is imminent, and will hopefully be out next Monday. The new release will fix this and several other bugs. It will also use an updated FlowUtils package, where all the C extensions now reside, and provide pre-built binaries (wheels) for all the common platforms & Python versions (3.7+). The main thing I am waiting on now is for someone to test the M1 Mac build since I don't have one to test locally.

**Comment by sbenz** [comment]
> Also, note that a new release of FlowKit (v0.9.0) is imminent, and will hopefully be out next Monday. The new release will fix this and several other bugs. It will also use an updated FlowUtils package, where all the C extensions now reside, and provide pre-built binaries (wheels) for all the common platforms & Python versions (3.7+). The main thing I am waiting on now is for someone to test the M1 Mac build since I don't have one to test locally.

This is great news! I have access to an M1 Mac if you still need someone to run through some examples with the build

**Comment by SalamHerkules** [comment]
Hi there, I just tested it and it works like a charm now! Thank you so much for your help.

Looking forward to the new FlowKit release!

**Comment by whitews** [comment]
@SalamHerkules Great, thanks for letting me know. I'll close this.

@sbenz Thanks for offering to help. I'll post in the Discussions for M1 help & we can continue there.
